Try to compile netifd with fighers scripts
/home/yejq/program/fighters/toolchains/bin/aarch64-buildroot-linux-musl-gcc   -I/home/yejq/program/fighters/target/staging/opt/wrtnet/include/libnl-tiny -O3 -DNDEBUG   -Wall -Werror -Wextra -Werror=implicit-function-declaration -Wformat -Werror=format-security -Werror=format-nonliteral -Os --std=gnu99 -Wmissing-declarations -Wno-unused-parameter -Wno-unused-but-set-parameter -Wimplicit-fallthrough -MD -MT CMakeFiles/netifd.dir/system-linux.c.o -MF CMakeFiles/netifd.dir/system-linux.c.o.d -o CMakeFiles/netifd.dir/system-linux.c.o -c /home/yejq/program/fighters/opensource/netifd/system-linux.c
/home/yejq/program/fighters/opensource/netifd/system-linux.c:82:10: fatal error: linux/ethtool_netlink.h: No such file or directory
   82 | #include <linux/ethtool_netlink.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/netifd.dir/build.make:454: CMakeFiles/netifd.dir/system-linux.c.o] Error 1
make[2]: Leaving directory '/home/yejq/program/fighters/opensource/netifd'
make[1]: *** [CMakeFiles/Makefile2:110: CMakeFiles/netifd.dir/all] Error 2
make[1]: Leaving directory '/home/yejq/program/fighters/opensource/netifd'
make: *** [Makefile:136: all] Error 2
Error, failed to build 'opensource/netifd'